### ISSUE TITLE
Commits groupe

### ISSUE THREAD

**Issue by DenisBeliant** [mlriedinger/Netfloux#9]
Denis : J'ai changé mon âge car j'ai maintenant 25 ans et demie. Louis à trouvé plus important de dire que j'ai bu beaucoup de Yop et effectivement, cela reflète bien plus ce que je suis réellement.

Marie-Laure à eu un moment de réflexion mais a aussi choisi la modification de Louis
https://github.com/DenisBeliant/Netfloux/commit/e79b4bd06c56689aba9bad89d173a2e7428ded15

@julienma

**Comment by mlriedinger** [comment]
J'ai enlevé le "z" de spaghetti 
https://github.com/mlriedinger/Netfloux/commit/e6c4e9282677fe45bfc9a9cd658b3c645a5c8a5e
@julienma

**Comment by Ducournl** [comment]
Modification la description de D'nis '<p>'Le Châtelard, 25ans, j'ai trop joué à Leap Day'</p>'
https://github.com/Ducournl/Netfloux/commit/6b092db06e43b663427c95056ec044de20c912b4
@julienma

**Comment by theocolombel** [comment]
J'ai changé jungle en spaghettiz  
https://github.com/theocolombel/Netfloux/commit/725de6f1cbfd571c88dfe2e99956c5da23b08de4

@julienma

**Comment by julienma** [comment]
Ok pour moi, merci @mlriedinger @DenisBeliant @Ducournl @theocolombel !
